import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Hero from "@/components/hero/Hero";
import Card from "@/components/card/Card";
import Category from "@/components/category/Category";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <Hero/>
      <Card/>
      <Category/>
      <Footer/>
        {children}
        </body>
    </html>
  );
}
